# Generated by Django 4.2.7 on 2024-11-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='end',
            field=models.IntegerField(verbose_name='Конечное значение'),
        ),
        migrations.AlterField(
            model_name='road',
            name='start',
            field=models.IntegerField(verbose_name='Начальное значение'),
        ),
    ]
