# Generated by Django 4.2.7 on 2024-10-22 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_payment_date_created_alter_road_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 13, 24, 21, 543104, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
