# Generated by Django 4.2.7 on 2024-10-15 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_payment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 12, 17, 21, 584814, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
