# Generated by Django 4.2.7 on 2024-10-23 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_payment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 8, 16, 4, 909649, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
